### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by hdmchl** [hadimichael/justaplan#1]
Okay, so here's the API that we're considering.

``` sass
.summary {
  @isPlan(number-of-columns) {
    @withColumn('.selector', bp size ...);
    @withOffset('.selector', bp size ...);
  }
}
```

Note: the grid is mobile first, so breakpoints are at that size and above (by default).

An example use-case would be to build out a 3 column layout of news summaries that are centered:

```
--------------------------------------------

    |----------|----------|----------|
    |          |          |          |
    |          |          |          |
    |          |          |          |
    |          |          |          |
    |          |          |          |
    |----------|----------|----------|

--------------------------------------------
```

You would build this using: 

``` html
<div class="news">
  <div class="news-item first-story">
    ...
  </div>
  <div class="news-item">
    ...
  </div>
  <div class="news-item">
    ...
  </div>
</div>
```

``` sass
.news {
  @include isPlan(11) { //the plan covers a total of 11 columns
    @include withColumn('.news-item', xxs 9, m 3); //a column with is 9 on xxs and 3 at medium and above
    @include withOffset('.first-story', xxs 1); //at bp xxs (and above), there will be a 1 column left-offset
  }
}
```

**Comment by lachlanmcdonald** [comment]
We could do an offset shorthand on the `withColumn` mixin.

So:

``` sass
@include withColumn('.news-item', xxs 9 1);
```

Would be the same as :

``` sass
@include withColumn('.news-item', xxs 9);
@include withOffset('.news-item', xxs 1);
```

**Comment by lachlanmcdonald** [comment]
Also, `new-plan`, `with-column` and `with-offset` are more SASSy naming conventions.

**Comment by hdmchl** [comment]
We can support the offset shorthand, but we'll still need a mechanism to add an offset to only 1 column. I think we can write it to support both.

So:

``` sass
@include with-column('.news-item', xxs 9 1); //every col will be 9 columns long, with 1 column left-offset
```

and all it does under-the-hood is call:

``` sass
@include with-offset('.news-item', xxs 9 1);
```

Yeah, fair call on naming. Let's go with hyphens.

**Comment by hdmchl** [comment]
Okay, good point from @keeganstreet: "what if you want to apply the column style to multiple selectors?"

Two approaches:
We pass in the full selector, e.g.:

``` sass
@include with-column('.news-item, .weather-item', xxs 9, m 3);
```

OR

We make the whole thing a bit more SASSy and put the selector outside (I like this approach):

``` sass
.news-item,
.weather-item {
  @include is-column(xxs 9, m 3);
}
```

New question: What if you call 'is-column' outside of a 'is-plan'? How do we get the total number of columns?

**Comment by lachlanmcdonald** [comment]
Agreed, I prefer the SASS syntax where `is-column` is agnostic to the selector being used. As for calls to `is-column` outside of `is-plan`, that is certainly trickier. Ideally, it wouldn't be allowed I would think.

As for what actually happens, SASS doesn't let us share variables between mixins, even if those mixins are called within the `@content` scope of another mixin. Interestingly enough, we can still set global variables as below:

``` sass
$__test: 0 !global;
@mixin test-a($i) {
    $__test: $i !global;
    @content;
}
@mixin test-b() {
    @debug $__test;
}
.test {
    @include test-a(1) {
        @include test-b;
    }
}
```

This happily outputs:

``` sass
DEBUG: 1
```

So, I would guess that `test-a` is executed, `@content` is reached and execution is paused to render what's in scope, then `test-a` is resumed. Theoretically then, unless we clear the global variable, any calls to `is-column` outside of the `is-plan` will just continue to use the global. We could set the global to `false`, and then throw an `@error` alert when that occurs if we wanted to.
